// Traductions des textes écrits directement dans les écrans (tx('English', 'Français')).
// Clé = le texte anglais. Espagnol, portugais du Brésil, allemand, italien — en tutoiement.
// Un texte absent ici s'affiche en anglais.
const TX = {
  es: {
    'Please accept the terms of use to continue.': 'Acepta las condiciones de uso para continuar.',
    'Check your email to confirm your account!': '¡Revisa tu email para confirmar tu cuenta!',
    'I accept the ': 'Acepto las ',
    'Terms of Use & Privacy Policy': 'Condiciones de uso y Política de privacidad',
    " of Snappin'Buddy": " de Snappin'Buddy",
    'Accept and continue': 'Aceptar y continuar',
    'On shoot': 'En sesión',
    'Unavailable': 'No disponible',
    'Available': 'Disponible',
    'VIDEO': 'VÍDEO',
    'View on Instagram →': 'Ver en Instagram →',
    'CURRENT PROJECT': 'PROYECTO ACTUAL',
    'ROLE': 'ROL',
    'UNIVERSE': 'UNIVERSO',
    'SHOOT ZONES': 'ZONAS DE SESIÓN',
    "✓ Proposal sent! Let's create something beautiful 🎨": '✓ ¡Propuesta enviada! Creemos algo bonito 🎨',
    'Tell them about your project...': 'Cuéntale tu proyecto...',
    'Sending...': 'Enviando...',
    '⚡ Send proposal': '⚡ Enviar propuesta',
    '⚡ Propose a collab': '⚡ Proponer una colaboración',
    'Report this user': 'Denunciar a este usuario',
    'Report sent, thank you.': 'Denuncia enviada, gracias.',
    'Why are you reporting this user?': '¿Por qué denuncias a este usuario?',
    'Inappropriate behavior': 'Comportamiento inapropiado',
    'Fake profile': 'Perfil falso',
    'Spam': 'Spam',
    'Harassment': 'Acoso',
    'Other': 'Otro',
    'Cancel': 'Cancelar',
    'Send report': 'Enviar',
    'Before you meet': 'Antes de quedar',
    "It all starts here... let's create something beautiful!": 'Todo empieza aquí... ¡creemos algo bonito!',
    'Message...': 'Mensaje...',
    'Maximum 5 portfolio photos': 'Máximo 5 fotos de portfolio',
    'Required fields missing': 'Faltan campos obligatorios',
    'Edit profile': 'Editar perfil',
    'Name': 'Nombre',
    'Your name or username': 'Tu nombre o usuario',
    'Area': 'Zona',
    'Shoreditch, Kreuzberg...': 'Malasaña, Lavapiés...',
    'Pitch': 'Pitch',
    'Current project...': 'Tu proyecto actual...',
    'ROLE *': 'ROL *',
    'VIDEO LINK': 'ENLACE DE VÍDEO',
    'Saving...': 'Guardando...',
    'Save': 'Guardar',
    '🔍 Search by username, role...': '🔍 Buscar por usuario, rol...',
    'All': 'Todos',
    'CREATIVE': 'CREATIVO',
    'View': 'Ver',
    'No results': 'Sin resultados',
    'Try a different search': 'Prueba otra búsqueda',
    'Me': 'Yo',
    'See profile & create together →': 'Ver perfil y crear juntos →',
    'Payment error, try again.': 'Error de pago, inténtalo de nuevo.',
    "⚡ Let's create something beautiful together! When shall we meet?": '⚡ ¡Creemos algo bonito juntos! ¿Cuándo quedamos?',
    'Accepted ✓': 'Aceptada ✓',
    'Declined': 'Rechazada',
    'Pending': 'Pendiente',
    'View profile': 'Ver perfil',
    'proposal(s)': 'propuesta(s)',
    'No proposals yet': 'Aún no hay propuestas',
    'Share your project to get proposals!': '¡Comparte tu proyecto para recibir propuestas!',
    'Open': 'Abierto',
    'Closed': 'Cerrado',
    'See proposals →': 'Ver propuestas →',
    'Edit': 'Editar',
    'Share': 'Compartir',
    '📍 City or country...': '📍 Ciudad o país...',
    'For you': 'Para ti',
    'Recent': 'Reciente',
    'MATCHING YOUR PROFILE': 'ENCAJA CON TU UNIVERSO',
    'Creative': 'Creativo',
    'Share on story': 'Compartir en historia',
    'No message': 'Sin mensaje',
    'en-GB': 'es-ES',
    'Following ✓': 'Siguiendo ✓',
    'Follow': 'Seguir',
    'Following': 'Seguidos',
    'No conversations yet': 'Aún no hay conversaciones',
    "Creatives you've already collaborated with": 'Creativos con los que ya has colaborado',
    'No buddies yet': 'Aún no tienes buddies',
    'Your accepted collabs will appear here!': '¡Tus colaboraciones aceptadas aparecerán aquí!',
    'Your private list of creatives to follow': 'Tu lista privada de creativos a seguir',
    'Nobody yet': 'Nadie todavía',
    'Follow creatives from Explore or Buddies!': '¡Sigue a creativos desde Explorar o Buddies!',
    'Edit project': 'Editar proyecto',
    'New project': 'Nuevo proyecto',
    'TITLE *': 'TÍTULO *',
    'Project title *': 'Título del proyecto *',
    'DESCRIPTION': 'DESCRIPCIÓN',
    'Describe your project...': 'Describe tu proyecto...',
    'WHO ARE YOU LOOKING FOR? *': '¿A QUIÉN BUSCAS? *',
    'City': 'Ciudad',
    'Launching...': 'Lanzando...',
    '✓ Save changes': '✓ Guardar cambios',
    '⚡ Launch project': '⚡ Lanzar proyecto',
    'Close project': 'Cerrar proyecto',
    'Please fill in all required fields.': 'Rellena todos los campos obligatorios.',
    'NAME OR USERNAME *': 'NOMBRE O USUARIO *',
    'Fill in your name and handle first.': 'Primero rellena tu nombre y tu usuario.',
    'Choose a role.': 'Elige un rol.',
    'Profile photo': 'Foto de perfil',
    'Role': 'Rol',
    'Universe': 'Universo',
    'Complete your profile to be found more easily!': '¡Completa tu perfil para que te encuentren más fácilmente!',
    'Good start! The more complete, the more you match': '¡Buen comienzo! Cuanto más completo, más matches',
    'Almost perfect!': '¡Casi perfecto!',
    'Complete profile 🔥 Ready to create something beautiful!': 'Perfil completo 🔥 ¡Listo para crear algo bonito!',
    'Profile strength': 'Nivel del perfil',
    'Video': 'Vídeo',
    'My projects': 'Mis proyectos',
    'active': 'en curso',
    '📸 Screenshot this card and share it on your story!': '📸 ¡Haz captura de esta tarjeta y compártela en tu historia!',
    '⚡ PROJECT': '⚡ PROYECTO',
    'LOOKING FOR': 'BUSCAMOS',
    'Join on': 'Únete en',
    'Join ⚡': 'Me apunto ⚡',
    'Hold down on the card to save it, then share on Instagram!': '¡Mantén pulsada la tarjeta para guardarla y compártela en Instagram!',
    'Close': 'Cerrar',
    'Choose a new password': 'Elige una nueva contraseña',
    'At least 6 characters.': 'Al menos 6 caracteres.',
    'New password': 'Nueva contraseña',
    'Confirm password': 'Confirma la contraseña',
    'Passwords do not match.': 'Las contraseñas no coinciden.',
    'Password too short (6 characters minimum).': 'Contraseña demasiado corta (mínimo 6 caracteres).',
    'Save password': 'Guardar contraseña',
    'Password updated! ✓': '¡Contraseña actualizada! ✓',
    'Continue to the app →': 'Continuar a la app →',
    'They will get an email. Once accepted, you can chat.': 'Recibirá un email. Cuando acepte, podréis chatear.',
    'Message': 'Escribir',
    'Proposal sent · waiting for a reply': 'Propuesta enviada · esperando respuesta',
    'They already sent you a proposal: reply in Match → 🤝': 'Ya te ha enviado una propuesta: responde en Match → 🤝',
    'Remember to generate and scan your QR codes in the tab': 'Acordaos de generar y escanear vuestros códigos QR en la pestaña',
    'Proposals you receive and send. Accept one to open the chat, then generate your QR code when you meet.': 'Las propuestas que recibes y envías. Acepta una para abrir el chat y genera tu código QR el día de la sesión.',
  },

  pt: {
    'Please accept the terms of use to continue.': 'Aceite os termos de uso para continuar.',
    'Check your email to confirm your account!': 'Verifique seu email para confirmar sua conta!',
    'I accept the ': 'Aceito os ',
    'Terms of Use & Privacy Policy': 'Termos de Uso e Política de Privacidade',
    " of Snappin'Buddy": " do Snappin'Buddy",
    'Accept and continue': 'Aceitar e continuar',
    'On shoot': 'Em ensaio',
    'Unavailable': 'Indisponível',
    'Available': 'Disponível',
    'VIDEO': 'VÍDEO',
    'View on Instagram →': 'Ver no Instagram →',
    'CURRENT PROJECT': 'PROJETO ATUAL',
    'ROLE': 'FUNÇÃO',
    'UNIVERSE': 'UNIVERSO',
    'SHOOT ZONES': 'ZONAS DE ENSAIO',
    "✓ Proposal sent! Let's create something beautiful 🎨": '✓ Proposta enviada! Vamos criar algo bonito 🎨',
    'Tell them about your project...': 'Conte sobre o seu projeto...',
    'Sending...': 'Enviando...',
    '⚡ Send proposal': '⚡ Enviar proposta',
    '⚡ Propose a collab': '⚡ Propor uma collab',
    'Report this user': 'Denunciar este usuário',
    'Report sent, thank you.': 'Denúncia enviada, obrigado.',
    'Why are you reporting this user?': 'Por que você está denunciando este usuário?',
    'Inappropriate behavior': 'Comportamento inadequado',
    'Fake profile': 'Perfil falso',
    'Spam': 'Spam',
    'Harassment': 'Assédio',
    'Other': 'Outro',
    'Cancel': 'Cancelar',
    'Send report': 'Enviar',
    'Before you meet': 'Antes do encontro',
    "It all starts here... let's create something beautiful!": 'Tudo começa aqui... vamos criar algo bonito!',
    'Message...': 'Mensagem...',
    'Maximum 5 portfolio photos': 'Máximo de 5 fotos no portfólio',
    'Required fields missing': 'Campos obrigatórios faltando',
    'Edit profile': 'Editar perfil',
    'Name': 'Nome',
    'Your name or username': 'Seu nome ou usuário',
    'Area': 'Região',
    'Shoreditch, Kreuzberg...': 'Vila Madalena, Lapa...',
    'Pitch': 'Pitch',
    'Current project...': 'Seu projeto atual...',
    'ROLE *': 'FUNÇÃO *',
    'VIDEO LINK': 'LINK DO VÍDEO',
    'Saving...': 'Salvando...',
    'Save': 'Salvar',
    '🔍 Search by username, role...': '🔍 Buscar por usuário, função...',
    'All': 'Todos',
    'CREATIVE': 'CRIATIVO',
    'View': 'Ver',
    'No results': 'Nenhum resultado',
    'Try a different search': 'Tente outra busca',
    'Me': 'Eu',
    'See profile & create together →': 'Ver perfil e criar juntos →',
    'Payment error, try again.': 'Erro no pagamento, tente de novo.',
    "⚡ Let's create something beautiful together! When shall we meet?": '⚡ Vamos criar algo bonito juntos! Quando a gente se encontra?',
    'Accepted ✓': 'Aceita ✓',
    'Declined': 'Recusada',
    'Pending': 'Pendente',
    'View profile': 'Ver perfil',
    'proposal(s)': 'proposta(s)',
    'No proposals yet': 'Nenhuma proposta ainda',
    'Share your project to get proposals!': 'Compartilhe seu projeto para receber propostas!',
    'Open': 'Aberto',
    'Closed': 'Fechado',
    'See proposals →': 'Ver propostas →',
    'Edit': 'Editar',
    'Share': 'Compartilhar',
    '📍 City or country...': '📍 Cidade ou país...',
    'For you': 'Para você',
    'Recent': 'Recentes',
    'MATCHING YOUR PROFILE': 'COMBINA COM O SEU UNIVERSO',
    'Creative': 'Criativo',
    'Share on story': 'Compartilhar nos stories',
    'No message': 'Sem mensagem',
    'en-GB': 'pt-BR',
    'Following ✓': 'Seguindo ✓',
    'Follow': 'Seguir',
    'Following': 'Seguindo',
    'No conversations yet': 'Nenhuma conversa ainda',
    "Creatives you've already collaborated with": 'Criativos com quem você já colaborou',
    'No buddies yet': 'Nenhum buddy ainda',
    'Your accepted collabs will appear here!': 'Suas collabs aceitas vão aparecer aqui!',
    'Your private list of creatives to follow': 'Sua lista privada de criativos para seguir',
    'Nobody yet': 'Ninguém ainda',
    'Follow creatives from Explore or Buddies!': 'Siga criativos pelo Explorar ou Buddies!',
    'Edit project': 'Editar projeto',
    'New project': 'Novo projeto',
    'TITLE *': 'TÍTULO *',
    'Project title *': 'Título do projeto *',
    'DESCRIPTION': 'DESCRIÇÃO',
    'Describe your project...': 'Descreva seu projeto...',
    'WHO ARE YOU LOOKING FOR? *': 'QUEM VOCÊ PROCURA? *',
    'City': 'Cidade',
    'Launching...': 'Lançando...',
    '✓ Save changes': '✓ Salvar alterações',
    '⚡ Launch project': '⚡ Lançar projeto',
    'Close project': 'Encerrar projeto',
    'Please fill in all required fields.': 'Preencha todos os campos obrigatórios.',
    'NAME OR USERNAME *': 'NOME OU USUÁRIO *',
    'Fill in your name and handle first.': 'Preencha primeiro seu nome e seu usuário.',
    'Choose a role.': 'Escolha uma função.',
    'Profile photo': 'Foto de perfil',
    'Role': 'Função',
    'Universe': 'Universo',
    'Complete your profile to be found more easily!': 'Complete seu perfil para ser encontrado mais facilmente!',
    'Good start! The more complete, the more you match': 'Bom começo! Quanto mais completo, mais matches',
    'Almost perfect!': 'Quase perfeito!',
    'Complete profile 🔥 Ready to create something beautiful!': 'Perfil completo 🔥 Pronto para criar algo bonito!',
    'Profile strength': 'Força do perfil',
    'Video': 'Vídeo',
    'My projects': 'Meus projetos',
    'active': 'em andamento',
    '📸 Screenshot this card and share it on your story!': '📸 Tire print deste card e compartilhe nos seus stories!',
    '⚡ PROJECT': '⚡ PROJETO',
    'LOOKING FOR': 'PROCURAMOS',
    'Join on': 'Participe no',
    'Join ⚡': 'Quero participar ⚡',
    'Hold down on the card to save it, then share on Instagram!': 'Segure o card para salvar e depois compartilhe no Instagram!',
    'Close': 'Fechar',
    'Choose a new password': 'Escolha uma nova senha',
    'At least 6 characters.': 'Pelo menos 6 caracteres.',
    'New password': 'Nova senha',
    'Confirm password': 'Confirme a senha',
    'Passwords do not match.': 'As senhas não coincidem.',
    'Password too short (6 characters minimum).': 'Senha muito curta (mínimo de 6 caracteres).',
    'Save password': 'Salvar senha',
    'Password updated! ✓': 'Senha atualizada! ✓',
    'Continue to the app →': 'Continuar para o app →',
    'They will get an email. Once accepted, you can chat.': 'A pessoa vai receber um e-mail. Quando aceitar, vocês podem conversar.',
    'Message': 'Escrever',
    'Proposal sent · waiting for a reply': 'Proposta enviada · aguardando resposta',
    'They already sent you a proposal: reply in Match → 🤝': 'Essa pessoa já te enviou uma proposta: responda em Match → 🤝',
    'Remember to generate and scan your QR codes in the tab': 'Lembrem de gerar e escanear os QR codes na aba',
    'Proposals you receive and send. Accept one to open the chat, then generate your QR code when you meet.': 'As propostas que você recebe e envia. Aceite uma para abrir o chat e gere seu QR code no dia do ensaio.',
  },

  de: {
    'Please accept the terms of use to continue.': 'Bitte akzeptiere die Nutzungsbedingungen, um fortzufahren.',
    'Check your email to confirm your account!': 'Schau in deine E-Mails, um dein Konto zu bestätigen!',
    'I accept the ': 'Ich akzeptiere die ',
    'Terms of Use & Privacy Policy': 'Nutzungsbedingungen & Datenschutzerklärung',
    " of Snappin'Buddy": " von Snappin'Buddy",
    'Accept and continue': 'Akzeptieren und weiter',
    'On shoot': 'Beim Shooting',
    'Unavailable': 'Nicht verfügbar',
    'Available': 'Verfügbar',
    'VIDEO': 'VIDEO',
    'View on Instagram →': 'Auf Instagram ansehen →',
    'CURRENT PROJECT': 'AKTUELLES PROJEKT',
    'ROLE': 'ROLLE',
    'UNIVERSE': 'UNIVERSUM',
    'SHOOT ZONES': 'SHOOTING-ZONEN',
    "✓ Proposal sent! Let's create something beautiful 🎨": '✓ Vorschlag gesendet! Lasst uns etwas Schönes erschaffen 🎨',
    'Tell them about your project...': 'Erzähl von deinem Projekt...',
    'Sending...': 'Wird gesendet...',
    '⚡ Send proposal': '⚡ Vorschlag senden',
    '⚡ Propose a collab': '⚡ Eine Collab vorschlagen',
    'Report this user': 'Diese Person melden',
    'Report sent, thank you.': 'Meldung gesendet, danke.',
    'Why are you reporting this user?': 'Warum meldest du diese Person?',
    'Inappropriate behavior': 'Unangemessenes Verhalten',
    'Fake profile': 'Fake-Profil',
    'Spam': 'Spam',
    'Harassment': 'Belästigung',
    'Other': 'Sonstiges',
    'Cancel': 'Abbrechen',
    'Send report': 'Senden',
    'Before you meet': 'Vor eurem Treffen',
    "It all starts here... let's create something beautiful!": 'Hier fängt alles an... lasst uns etwas Schönes erschaffen!',
    'Message...': 'Nachricht...',
    'Maximum 5 portfolio photos': 'Maximal 5 Portfolio-Fotos',
    'Required fields missing': 'Pflichtfelder fehlen',
    'Edit profile': 'Profil bearbeiten',
    'Name': 'Name',
    'Your name or username': 'Dein Name oder Username',
    'Area': 'Gegend',
    'Shoreditch, Kreuzberg...': 'Kreuzberg, Schanzenviertel...',
    'Pitch': 'Pitch',
    'Current project...': 'Dein aktuelles Projekt...',
    'ROLE *': 'ROLLE *',
    'VIDEO LINK': 'VIDEO-LINK',
    'Saving...': 'Wird gespeichert...',
    'Save': 'Speichern',
    '🔍 Search by username, role...': '🔍 Nach Username, Rolle suchen...',
    'All': 'Alle',
    'CREATIVE': 'KREATIVE',
    'View': 'Ansehen',
    'No results': 'Keine Ergebnisse',
    'Try a different search': 'Versuch eine andere Suche',
    'Me': 'Ich',
    'See profile & create together →': 'Profil ansehen & zusammen kreieren →',
    'Payment error, try again.': 'Zahlungsfehler, versuch es noch einmal.',
    "⚡ Let's create something beautiful together! When shall we meet?": '⚡ Lass uns zusammen etwas Schönes erschaffen! Wann treffen wir uns?',
    'Accepted ✓': 'Angenommen ✓',
    'Declined': 'Abgelehnt',
    'Pending': 'Ausstehend',
    'View profile': 'Profil ansehen',
    'proposal(s)': 'Vorschlag/Vorschläge',
    'No proposals yet': 'Noch keine Vorschläge',
    'Share your project to get proposals!': 'Teile dein Projekt, um Vorschläge zu bekommen!',
    'Open': 'Offen',
    'Closed': 'Geschlossen',
    'See proposals →': 'Vorschläge ansehen →',
    'Edit': 'Bearbeiten',
    'Share': 'Teilen',
    '📍 City or country...': '📍 Stadt oder Land...',
    'For you': 'Für dich',
    'Recent': 'Neueste',
    'MATCHING YOUR PROFILE': 'PASST ZU DEINEM UNIVERSUM',
    'Creative': 'Kreative:r',
    'Share on story': 'In der Story teilen',
    'No message': 'Keine Nachricht',
    'en-GB': 'de-DE',
    'Following ✓': 'Folgst du ✓',
    'Follow': 'Folgen',
    'Following': 'Gefolgt',
    'No conversations yet': 'Noch keine Unterhaltungen',
    "Creatives you've already collaborated with": 'Kreative, mit denen du schon zusammengearbeitet hast',
    'No buddies yet': 'Noch keine Buddies',
    'Your accepted collabs will appear here!': 'Deine angenommenen Collabs erscheinen hier!',
    'Your private list of creatives to follow': 'Deine private Liste von Kreativen, denen du folgst',
    'Nobody yet': 'Noch niemand',
    'Follow creatives from Explore or Buddies!': 'Folge Kreativen über Entdecken oder Buddies!',
    'Edit project': 'Projekt bearbeiten',
    'New project': 'Neues Projekt',
    'TITLE *': 'TITEL *',
    'Project title *': 'Projekttitel *',
    'DESCRIPTION': 'BESCHREIBUNG',
    'Describe your project...': 'Beschreib dein Projekt...',
    'WHO ARE YOU LOOKING FOR? *': 'WEN SUCHST DU? *',
    'City': 'Stadt',
    'Launching...': 'Wird gestartet...',
    '✓ Save changes': '✓ Änderungen speichern',
    '⚡ Launch project': '⚡ Projekt starten',
    'Close project': 'Projekt schließen',
    'Please fill in all required fields.': 'Bitte fülle alle Pflichtfelder aus.',
    'NAME OR USERNAME *': 'NAME ODER USERNAME *',
    'Fill in your name and handle first.': 'Gib zuerst deinen Namen und dein Handle ein.',
    'Choose a role.': 'Wähle eine Rolle.',
    'Profile photo': 'Profilfoto',
    'Role': 'Rolle',
    'Universe': 'Universum',
    'Complete your profile to be found more easily!': 'Vervollständige dein Profil, damit man dich leichter findet!',
    'Good start! The more complete, the more you match': 'Guter Anfang! Je vollständiger, desto mehr Matches',
    'Almost perfect!': 'Fast perfekt!',
    'Complete profile 🔥 Ready to create something beautiful!': 'Profil vollständig 🔥 Bereit, etwas Schönes zu erschaffen!',
    'Profile strength': 'Profilstärke',
    'Video': 'Video',
    'My projects': 'Meine Projekte',
    'active': 'aktiv',
    '📸 Screenshot this card and share it on your story!': '📸 Mach einen Screenshot dieser Karte und teile sie in deiner Story!',
    '⚡ PROJECT': '⚡ PROJEKT',
    'LOOKING FOR': 'GESUCHT',
    'Join on': 'Mach mit auf',
    'Join ⚡': 'Ich bin dabei ⚡',
    'Hold down on the card to save it, then share on Instagram!': 'Halte die Karte gedrückt, um sie zu speichern, und teile sie auf Instagram!',
    'Close': 'Schließen',
    'Choose a new password': 'Wähle ein neues Passwort',
    'At least 6 characters.': 'Mindestens 6 Zeichen.',
    'New password': 'Neues Passwort',
    'Confirm password': 'Passwort bestätigen',
    'Passwords do not match.': 'Die Passwörter stimmen nicht überein.',
    'Password too short (6 characters minimum).': 'Passwort zu kurz (mindestens 6 Zeichen).',
    'Save password': 'Passwort speichern',
    'Password updated! ✓': 'Passwort aktualisiert! ✓',
    'Continue to the app →': 'Weiter zur App →',
    'They will get an email. Once accepted, you can chat.': 'Die Person bekommt eine E-Mail. Sobald sie annimmt, könnt ihr chatten.',
    'Message': 'Schreiben',
    'Proposal sent · waiting for a reply': 'Vorschlag gesendet · wartet auf Antwort',
    'They already sent you a proposal: reply in Match → 🤝': 'Diese Person hat dir schon einen Vorschlag geschickt: antworte unter Match → 🤝',
    'Remember to generate and scan your QR codes in the tab': 'Denkt daran, eure QR-Codes im Tab zu erstellen und zu scannen',
    'Proposals you receive and send. Accept one to open the chat, then generate your QR code when you meet.': 'Deine empfangenen und gesendeten Vorschläge. Nimm einen an, um den Chat zu öffnen, und erstelle beim Treffen deinen QR-Code.',
  },

  it: {
    'Please accept the terms of use to continue.': 'Accetta le condizioni d’uso per continuare.',
    'Check your email to confirm your account!': 'Controlla la tua email per confermare l’account!',
    'I accept the ': 'Accetto i ',
    'Terms of Use & Privacy Policy': 'Termini d’uso e Informativa sulla privacy',
    " of Snappin'Buddy": " di Snappin'Buddy",
    'Accept and continue': 'Accetta e continua',
    'On shoot': 'In shooting',
    'Unavailable': 'Non disponibile',
    'Available': 'Disponibile',
    'VIDEO': 'VIDEO',
    'View on Instagram →': 'Guarda su Instagram →',
    'CURRENT PROJECT': 'PROGETTO ATTUALE',
    'ROLE': 'RUOLO',
    'UNIVERSE': 'UNIVERSO',
    'SHOOT ZONES': 'ZONE DI SHOOTING',
    "✓ Proposal sent! Let's create something beautiful 🎨": '✓ Proposta inviata! Creiamo qualcosa di bello 🎨',
    'Tell them about your project...': 'Raccontagli il tuo progetto...',
    'Sending...': 'Invio...',
    '⚡ Send proposal': '⚡ Invia la proposta',
    '⚡ Propose a collab': '⚡ Proponi una collab',
    'Report this user': 'Segnala questo utente',
    'Report sent, thank you.': 'Segnalazione inviata, grazie.',
    'Why are you reporting this user?': 'Perché segnali questo utente?',
    'Inappropriate behavior': 'Comportamento inappropriato',
    'Fake profile': 'Profilo falso',
    'Spam': 'Spam',
    'Harassment': 'Molestie',
    'Other': 'Altro',
    'Cancel': 'Annulla',
    'Send report': 'Invia',
    'Before you meet': 'Prima di incontrarvi',
    "It all starts here... let's create something beautiful!": 'Tutto inizia qui... creiamo qualcosa di bello!',
    'Message...': 'Messaggio...',
    'Maximum 5 portfolio photos': 'Massimo 5 foto nel portfolio',
    'Required fields missing': 'Campi obbligatori mancanti',
    'Edit profile': 'Modifica profilo',
    'Name': 'Nome',
    'Your name or username': 'Il tuo nome o username',
    'Area': 'Zona',
    'Shoreditch, Kreuzberg...': 'Navigli, Trastevere...',
    'Pitch': 'Pitch',
    'Current project...': 'Il tuo progetto attuale...',
    'ROLE *': 'RUOLO *',
    'VIDEO LINK': 'LINK VIDEO',
    'Saving...': 'Salvataggio...',
    'Save': 'Salva',
    '🔍 Search by username, role...': '🔍 Cerca per username, ruolo...',
    'All': 'Tutti',
    'CREATIVE': 'CREATIVO',
    'View': 'Vedi',
    'No results': 'Nessun risultato',
    'Try a different search': 'Prova un’altra ricerca',
    'Me': 'Io',
    'See profile & create together →': 'Vedi il profilo e create insieme →',
    'Payment error, try again.': 'Errore di pagamento, riprova.',
    "⚡ Let's create something beautiful together! When shall we meet?": '⚡ Creiamo qualcosa di bello insieme! Quando ci vediamo?',
    'Accepted ✓': 'Accettata ✓',
    'Declined': 'Rifiutata',
    'Pending': 'In attesa',
    'View profile': 'Vedi profilo',
    'proposal(s)': 'proposta/e',
    'No proposals yet': 'Ancora nessuna proposta',
    'Share your project to get proposals!': 'Condividi il tuo progetto per ricevere proposte!',
    'Open': 'Aperto',
    'Closed': 'Chiuso',
    'See proposals →': 'Vedi proposte →',
    'Edit': 'Modifica',
    'Share': 'Condividi',
    '📍 City or country...': '📍 Città o paese...',
    'For you': 'Per te',
    'Recent': 'Recenti',
    'MATCHING YOUR PROFILE': 'IN LINEA CON IL TUO UNIVERSO',
    'Creative': 'Creativo',
    'Share on story': 'Condividi nelle storie',
    'No message': 'Nessun messaggio',
    'en-GB': 'it-IT',
    'Following ✓': 'Segui già ✓',
    'Follow': 'Segui',
    'Following': 'Seguiti',
    'No conversations yet': 'Ancora nessuna conversazione',
    "Creatives you've already collaborated with": 'Creativi con cui hai già collaborato',
    'No buddies yet': 'Ancora nessun buddy',
    'Your accepted collabs will appear here!': 'Le tue collab accettate appariranno qui!',
    'Your private list of creatives to follow': 'La tua lista privata di creativi da seguire',
    'Nobody yet': 'Ancora nessuno',
    'Follow creatives from Explore or Buddies!': 'Segui i creativi da Esplora o Buddies!',
    'Edit project': 'Modifica progetto',
    'New project': 'Nuovo progetto',
    'TITLE *': 'TITOLO *',
    'Project title *': 'Titolo del progetto *',
    'DESCRIPTION': 'DESCRIZIONE',
    'Describe your project...': 'Descrivi il tuo progetto...',
    'WHO ARE YOU LOOKING FOR? *': 'CHI CERCHI? *',
    'City': 'Città',
    'Launching...': 'Lancio in corso...',
    '✓ Save changes': '✓ Salva modifiche',
    '⚡ Launch project': '⚡ Lancia il progetto',
    'Close project': 'Chiudi il progetto',
    'Please fill in all required fields.': 'Compila tutti i campi obbligatori.',
    'NAME OR USERNAME *': 'NOME O USERNAME *',
    'Fill in your name and handle first.': 'Inserisci prima il tuo nome e il tuo handle.',
    'Choose a role.': 'Scegli un ruolo.',
    'Profile photo': 'Foto profilo',
    'Role': 'Ruolo',
    'Universe': 'Universo',
    'Complete your profile to be found more easily!': 'Completa il profilo per farti trovare più facilmente!',
    'Good start! The more complete, the more you match': 'Buon inizio! Più è completo, più match fai',
    'Almost perfect!': 'Quasi perfetto!',
    'Complete profile 🔥 Ready to create something beautiful!': 'Profilo completo 🔥 Pronto a creare qualcosa di bello!',
    'Profile strength': 'Forza del profilo',
    'Video': 'Video',
    'My projects': 'I miei progetti',
    'active': 'in corso',
    '📸 Screenshot this card and share it on your story!': '📸 Fai uno screenshot di questa card e condividila nelle storie!',
    '⚡ PROJECT': '⚡ PROGETTO',
    'LOOKING FOR': 'CERCHIAMO',
    'Join on': 'Unisciti su',
    'Join ⚡': 'Ci sto ⚡',
    'Hold down on the card to save it, then share on Instagram!': 'Tieni premuta la card per salvarla, poi condividila su Instagram!',
    'Close': 'Chiudi',
    'Choose a new password': 'Scegli una nuova password',
    'At least 6 characters.': 'Almeno 6 caratteri.',
    'New password': 'Nuova password',
    'Confirm password': 'Conferma la password',
    'Passwords do not match.': 'Le password non corrispondono.',
    'Password too short (6 characters minimum).': 'Password troppo corta (minimo 6 caratteri).',
    'Save password': 'Salva la password',
    'Password updated! ✓': 'Password aggiornata! ✓',
    'Continue to the app →': 'Continua nell’app →',
    'They will get an email. Once accepted, you can chat.': 'Riceverà un’email. Quando accetta, potrete chattare.',
    'Message': 'Scrivi',
    'Proposal sent · waiting for a reply': 'Proposta inviata · in attesa di risposta',
    'They already sent you a proposal: reply in Match → 🤝': 'Ti ha già inviato una proposta: rispondi in Match → 🤝',
    'Remember to generate and scan your QR codes in the tab': 'Ricordatevi di generare e scansionare i vostri QR code nella scheda',
    'Proposals you receive and send. Accept one to open the chat, then generate your QR code when you meet.': 'Le proposte che ricevi e invii. Accettane una per aprire la chat, poi genera il tuo QR code il giorno dello shooting.',
  },
};

export default TX;
