// Traductions des textes écrits directement dans les écrans (tx('English', 'Français')).
// Clé = le texte anglais. Espagnol, portugais du Brésil, allemand, italien — en tutoiement.
// Un texte absent ici s'affiche en anglais.
const TX = {
  es: {
    'Check your emails': 'Revisa tus emails',
    'We sent a confirmation link to': 'Hemos enviado un enlace de confirmación a',
    'Click the link to activate your account, then come back here. Check your spam folder if you don’t see it.': 'Haz clic en el enlace para activar tu cuenta y vuelve aquí. Mira en spam si no lo ves.',
    'Link sent again ✓': 'Enlace reenviado ✓',
    'Resend the link': 'Reenviar el enlace',
    'Back to sign in': 'Volver a iniciar sesión',
    'validated projects': 'proyectos validados',
    'validated project': 'proyecto validado',
    'Real meetings, confirmed on the spot': 'Encuentros reales, confirmados en el momento',
    'You blocked this person. They can no longer contact you or see your profile.': 'Has bloqueado a esta persona. Ya no puede contactarte ni ver tu perfil.',
    'Unblock': 'Desbloquear',
    'Block this person': 'Bloquear a esta persona',
    'They won’t be able to message you, propose a collab, or see you on the map. You can undo this at any time.': 'No podrá escribirte, proponerte una colaboración ni verte en el mapa. Puedes deshacerlo cuando quieras.',
    'Block': 'Bloquear',
    'Visible on your profile': 'Visible en tu perfil',
    'Scan your buddy’s QR when you meet to validate a project': 'Escanea el QR de tu buddy al encontraros para validar un proyecto',
    'Blocked accounts': 'Cuentas bloqueadas',
    'Loading…': 'Cargando…',
    'You haven’t blocked anyone.': 'No has bloqueado a nadie.',
    'Sign out on all devices': 'Cerrar sesión en todos los dispositivos',
    'Sign in first': 'Inicia sesión primero',
    'Log in and scan the QR again.': 'Inicia sesión y escanea el QR de nuevo.',
    'That’s your own QR': 'Es tu propio QR',
    'Scan the other person’s QR, not yours.': 'Escanea el QR de la otra persona, no el tuyo.',
    'This QR has expired': 'Este QR ha caducado',
    'QR codes last 30 minutes. Ask for a new one.': 'Los QR duran 30 minutos. Pide uno nuevo.',
    'Not your collab': 'No es tu colaboración',
    'This QR belongs to a project you’re not part of.': 'Este QR pertenece a un proyecto del que no formas parte.',
    'QR not recognised': 'QR no reconocido',
    'This code doesn’t match any meeting.': 'Este código no corresponde a ningún encuentro.',
    'Something went wrong': 'Algo ha fallado',
    'Try scanning again.': 'Vuelve a escanear.',
    'your buddy': 'tu buddy',
    'Already validated': 'Ya validado',
    'Meeting validated!': '¡Encuentro validado!',
    'Share your shoot': 'Comparte vuestro shoot',
    'Post a photo from today in your story, tag @snappinbuddy and add #snappinbuddy — the best collabs get reposted on our page.': 'Publica una foto de hoy en tu historia, etiqueta a @snappinbuddy y añade #snappinbuddy — las mejores colaboraciones se repostean en nuestra página.',
    'Caption copied ✓': 'Texto copiado ✓',
    'Copy the caption': 'Copiar el texto',
    'Back to the app': 'Volver a la app',
    'Sign out': 'Cerrar sesión',
    'Share my profile': 'Compartir mi perfil',
    'ROLES': 'ROLES',
    'Create with me ⚡': 'Creemos juntos ⚡',
    'Share your profile on your story 📸': 'Comparte tu perfil en tu historia 📸',
    'Press and hold the image to save it': 'Mantén pulsada la imagen para guardarla',
    'Preparing…': 'Preparando…',
    '📸 Save the image': '📸 Guardar la imagen',
    'Link copied ✓': 'Enlace copiado ✓',
    '🔗 Copy my link': '🔗 Copiar mi enlace',
    'Account deleted': 'Cuenta eliminada',
    'Deleted account': 'Cuenta eliminada',
    'This person deleted their account. The conversation stays here, but you can no longer reply.': 'Esta persona eliminó su cuenta. La conversación sigue aquí, pero ya no puedes responder.',
    'Please confirm your age and accept the terms to continue.': 'Confirma tu edad y acepta las condiciones para continuar.',
    'I confirm I am 18 or over': 'Confirmo que tengo 18 años o más',
    ' and I accept the ': ' y acepto las ',
    'This handle is not allowed.': 'Este handle no está permitido.',
    'This handle is not allowed': 'Este handle no está permitido',
    'This handle is reserved': 'Este handle está reservado',
    'Couldn\'t send the photo. Try again.': 'No se pudo enviar la foto. Inténtalo de nuevo.',
    '📷 Photo': '📷 Foto',
    'Shared photo': 'Foto compartida',
    'Send a photo': 'Enviar una foto',
    'Open to save': 'Abrir para guardar',
    'Your handle needs at least 3 characters.': 'Tu handle debe tener al menos 3 caracteres.',
    'This handle is already taken.': 'Este handle ya está en uso.',
    'At least 3 characters: letters, numbers, . or _': 'Mínimo 3 caracteres: letras, números, . o _',
    'Checking…': 'Comprobando…',
    'Already taken': 'Ya está en uso',
    '🔍 Search @handle, name, role...': '🔍 Busca un @handle, nombre, rol...',
    'Tap the link': 'Toca el enlace',
    'Apply ⚡': 'Postúlate ⚡',
    'Terms of Use & Privacy Policy': 'Condiciones de uso y Política de privacidad',
    " of Snappin'Buddy": " de Snappin'Buddy",
    'Accept and continue': 'Aceptar y continuar',
    'On shoot': 'En sesión',
    'Unavailable': 'No disponible',
    'Available': 'Disponible',
    'VIDEO': 'VÍDEO',
    'View on Instagram →': 'Ver en Instagram →',
    'CURRENT PROJECT': 'PROYECTO ACTUAL',
    'ROLE': 'ROL',
    'UNIVERSE': 'UNIVERSO',
    'AREAS': 'ZONAS',
    "✓ Proposal sent! Let's create something beautiful 🎨": '✓ ¡Propuesta enviada! Creemos algo bonito 🎨',
    'Tell them about your project...': 'Cuéntale tu proyecto...',
    'Sending...': 'Enviando...',
    '⚡ Send proposal': '⚡ Enviar propuesta',
    '⚡ Propose a collab': '⚡ Proponer una colaboración',
    'Report this user': 'Denunciar a este usuario',
    'Report sent, thank you.': 'Denuncia enviada, gracias.',
    'Why are you reporting this user?': '¿Por qué denuncias a este usuario?',
    'Inappropriate behavior': 'Comportamiento inapropiado',
    'Fake profile': 'Perfil falso',
    'Spam': 'Spam',
    'Harassment': 'Acoso',
    'Other': 'Otro',
    'Cancel': 'Cancelar',
    'Send report': 'Enviar',
    'Before you meet': 'Antes de quedar',
    "It all starts here... let's create something beautiful!": 'Todo empieza aquí... ¡creemos algo bonito!',
    'Message...': 'Mensaje...',
    'Maximum 5 portfolio photos': 'Máximo 5 fotos de portfolio',
    'Required fields missing': 'Faltan campos obligatorios',
    'Edit profile': 'Editar perfil',
    'Name': 'Nombre',
    'Your name or username': 'Tu nombre o usuario',
    'Area': 'Zona',
    'Shoreditch, Kreuzberg...': 'Malasaña, Lavapiés...',
    'Pitch': 'Pitch',
    'Current project...': 'Tu proyecto actual...',
    'VIDEO LINK': 'ENLACE DE VÍDEO',
    'Saving...': 'Guardando...',
    'Save': 'Guardar',
    'All': 'Todos',
    'CREATIVE': 'CREATIVO',
    'View': 'Ver',
    'No results': 'Sin resultados',
    'Try a different search': 'Prueba otra búsqueda',
    'Me': 'Yo',
    'See profile & create together →': 'Ver perfil y crear juntos →',
    'Payment error, try again.': 'Error de pago, inténtalo de nuevo.',
    "⚡ Let's create something beautiful together! When shall we meet?": '⚡ ¡Creemos algo bonito juntos! ¿Cuándo quedamos?',
    'Accepted ✓': 'Aceptada ✓',
    'Declined': 'Rechazada',
    'Pending': 'Pendiente',
    'View profile': 'Ver perfil',
    'proposal(s)': 'propuesta(s)',
    'No proposals yet': 'Aún no hay propuestas',
    'Share your project to get proposals!': '¡Comparte tu proyecto para recibir propuestas!',
    'Open': 'Abierto',
    'Closed': 'Cerrado',
    'See proposals →': 'Ver propuestas →',
    'Edit': 'Editar',
    'Share': 'Compartir',
    '📍 City or country...': '📍 Ciudad o país...',
    'For you': 'Para ti',
    'Recent': 'Reciente',
    'MATCHING YOUR PROFILE': 'ENCAJA CON TU UNIVERSO',
    'Creative': 'Creativo',
    'Share on story': 'Compartir en historia',
    'No message': 'Sin mensaje',
    'en-GB': 'es-ES',
    'Following ✓': 'Siguiendo ✓',
    'Follow': 'Seguir',
    'Following': 'Seguidos',
    'No conversations yet': 'Aún no hay conversaciones',
    "Creatives you've already collaborated with": 'Creativos con los que ya has colaborado',
    'No buddies yet': 'Aún no tienes buddies',
    'Your accepted collabs will appear here!': '¡Tus colaboraciones aceptadas aparecerán aquí!',
    'Your private list of creatives to follow': 'Tu lista privada de creativos a seguir',
    'Nobody yet': 'Nadie todavía',
    'Follow creatives from Explore or Buddies!': '¡Sigue a creativos desde Explorar o Buddies!',
    'Edit project': 'Editar proyecto',
    'New project': 'Nuevo proyecto',
    'TITLE *': 'TÍTULO *',
    'Project title *': 'Título del proyecto *',
    'DESCRIPTION': 'DESCRIPCIÓN',
    'Describe your project...': 'Describe tu proyecto...',
    'WHO ARE YOU LOOKING FOR? *': '¿A QUIÉN BUSCAS? *',
    'City': 'Ciudad',
    'Launching...': 'Lanzando...',
    '✓ Save changes': '✓ Guardar cambios',
    '⚡ Launch project': '⚡ Lanzar proyecto',
    'Close project': 'Cerrar proyecto',
    'Please fill in all required fields.': 'Rellena todos los campos obligatorios.',
    'NAME OR USERNAME *': 'NOMBRE O USUARIO *',
    'Fill in your name and handle first.': 'Primero rellena tu nombre y tu usuario.',
    'Profile photo': 'Foto de perfil',
    'Role': 'Rol',
    'Universe': 'Universo',
    'Complete your profile to be found more easily!': '¡Completa tu perfil para que te encuentren más fácilmente!',
    'Good start! The more complete, the more you match': '¡Buen comienzo! Cuanto más completo, más matches',
    'Almost perfect!': '¡Casi perfecto!',
    'Complete profile 🔥 Ready to create something beautiful!': 'Perfil completo 🔥 ¡Listo para crear algo bonito!',
    'Profile strength': 'Nivel del perfil',
    'Video': 'Vídeo',
    'My projects': 'Mis proyectos',
    'active': 'en curso',
    '📸 Screenshot this card and share it on your story!': '📸 ¡Haz captura de esta tarjeta y compártela en tu historia!',
    '⚡ PROJECT': '⚡ PROYECTO',
    'LOOKING FOR': 'BUSCAMOS',
    'Join ⚡': 'Me apunto ⚡',
    'Close': 'Cerrar',
    'Choose a new password': 'Elige una nueva contraseña',
    'At least 6 characters.': 'Al menos 6 caracteres.',
    'New password': 'Nueva contraseña',
    'Confirm password': 'Confirma la contraseña',
    'Passwords do not match.': 'Las contraseñas no coinciden.',
    'Password too short (6 characters minimum).': 'Contraseña demasiado corta (mínimo 6 caracteres).',
    'Save password': 'Guardar contraseña',
    'Password updated! ✓': '¡Contraseña actualizada! ✓',
    'Continue to the app →': 'Continuar a la app →',
    'They will get an email. Once accepted, you can chat.': 'Recibirá un email. Cuando acepte, podréis chatear.',
    'Message': 'Escribir',
    'Proposal sent · waiting for a reply': 'Propuesta enviada · esperando respuesta',
    'They already sent you a proposal: reply in Match → 🤝': 'Ya te ha enviado una propuesta: responde en Match → 🤝',
    'Remember to generate and scan your QR codes in the tab': 'Acordaos de generar y escanear vuestros códigos QR en la pestaña',
    'Proposals you receive and send. Accept one to open the chat, then generate your QR code when you meet.': 'Las propuestas que recibes y envías. Acepta una para abrir el chat y genera tu código QR el día de la sesión.',
    'Reopen project': 'Reabrir el proyecto',
    'Deleting...': 'Eliminando...',
    'Tap again to delete for good': 'Pulsa otra vez para eliminarlo definitivamente',
    'Delete project': 'Eliminar el proyecto',
    'Could not delete the project, try again.': 'No se pudo eliminar el proyecto, inténtalo de nuevo.',
    'Save the card': 'Guardar la tarjeta',
    'Press and hold the image to save it, then share it on your story!': 'Mantén pulsada la imagen para guardarla y compártela en tu story.',
    '✓ Collab done': '✓ Collab realizada',
    'You': 'Tú',
    'Message deleted': 'Mensaje eliminado',
    'Replying to': 'Respondiendo a',
    'you': 'ti',
    'Copied ✓': 'Copiado ✓',
    'Reply': 'Responder',
    'Copy text': 'Copiar el texto',
    'Delete': 'Eliminar',
    'edited': 'editado',
    'Editing your message': 'Editando tu mensaje',
    'Forward to': 'Reenviar a',
    'No buddies to forward to yet.': 'Aún no tienes buddies a quienes reenviar.',
    'Pick an emoji': 'Elegir un emoji',
    'Forward': 'Reenviar',
    'Unpin': 'Quitar de fijados',
    'Pin': 'Fijar',
    'Read receipts': 'Confirmaciones de lectura',
    'Let others see when you read their messages.': 'Deja que los demás vean cuándo lees sus mensajes.',
    'ROLES *': 'ROLES *',
    'Pick up to 3.': 'Elige hasta 3.',
    'You can pick up to 3.': 'Puedes elegir hasta 3.',
    'Choose at least one role.': 'Elige al menos un rol.',
    'This screen had a problem': 'Esta pantalla tuvo un problema',
    'The rest of the app still works. Reload to try again.': 'El resto de la app funciona. Recarga para volver a intentarlo.',
    'Reload': 'Recargar',
    'Shared project': 'Proyecto compartido',
    'Tap the link to apply': 'Toca el enlace para postular',
    'Preparing...': 'Preparando...',
    '⬇️ Save the image': '⬇️ Guardar la imagen',
    '🔗 Copy the link': '🔗 Copiar el enlace',
    '1. Save the image, then post it on your story.': '1. Guarda la imagen y publícala en tu story.',
    '2. Copy the link, then add the link sticker and paste it.': '2. Copia el enlace, añade el sticker de enlace y pégalo.',
    '3. Anyone who taps it lands on this exact project.': '3. Quien lo toque llega directamente a este proyecto.',
    'Press and hold the image to save it.': 'Mantén pulsada la imagen para guardarla.',
  },

  pt: {
    'Check your emails': 'Confira seus emails',
    'We sent a confirmation link to': 'Enviamos um link de confirmação para',
    'Click the link to activate your account, then come back here. Check your spam folder if you don’t see it.': 'Clique no link para ativar sua conta e volte aqui. Olhe no spam se não achar.',
    'Link sent again ✓': 'Link reenviado ✓',
    'Resend the link': 'Reenviar o link',
    'Back to sign in': 'Voltar para o login',
    'validated projects': 'projetos validados',
    'validated project': 'projeto validado',
    'Real meetings, confirmed on the spot': 'Encontros reais, confirmados na hora',
    'You blocked this person. They can no longer contact you or see your profile.': 'Você bloqueou essa pessoa. Ela não pode mais te contatar nem ver seu perfil.',
    'Unblock': 'Desbloquear',
    'Block this person': 'Bloquear essa pessoa',
    'They won’t be able to message you, propose a collab, or see you on the map. You can undo this at any time.': 'Ela não poderá te escrever, propor uma collab nem te ver no mapa. Você pode desfazer quando quiser.',
    'Block': 'Bloquear',
    'Visible on your profile': 'Visível no seu perfil',
    'Scan your buddy’s QR when you meet to validate a project': 'Escaneie o QR do seu buddy no encontro para validar um projeto',
    'Blocked accounts': 'Contas bloqueadas',
    'Loading…': 'Carregando…',
    'You haven’t blocked anyone.': 'Você não bloqueou ninguém.',
    'Sign out on all devices': 'Sair de todos os dispositivos',
    'Sign in first': 'Entre na sua conta primeiro',
    'Log in and scan the QR again.': 'Entre e escaneie o QR de novo.',
    'That’s your own QR': 'Esse é o seu próprio QR',
    'Scan the other person’s QR, not yours.': 'Escaneie o QR da outra pessoa, não o seu.',
    'This QR has expired': 'Esse QR expirou',
    'QR codes last 30 minutes. Ask for a new one.': 'Os QR duram 30 minutos. Peça um novo.',
    'Not your collab': 'Não é a sua collab',
    'This QR belongs to a project you’re not part of.': 'Esse QR é de um projeto do qual você não faz parte.',
    'QR not recognised': 'QR não reconhecido',
    'This code doesn’t match any meeting.': 'Esse código não corresponde a nenhum encontro.',
    'Something went wrong': 'Algo deu errado',
    'Try scanning again.': 'Tente escanear de novo.',
    'your buddy': 'seu buddy',
    'Already validated': 'Já validado',
    'Meeting validated!': 'Encontro validado!',
    'Share your shoot': 'Compartilhem o shoot',
    'Post a photo from today in your story, tag @snappinbuddy and add #snappinbuddy — the best collabs get reposted on our page.': 'Poste uma foto de hoje no story, marque @snappinbuddy e use #snappinbuddy — as melhores collabs vão pro nosso perfil.',
    'Caption copied ✓': 'Legenda copiada ✓',
    'Copy the caption': 'Copiar a legenda',
    'Back to the app': 'Voltar para o app',
    'Sign out': 'Sair',
    'Share my profile': 'Compartilhar meu perfil',
    'ROLES': 'FUNÇÕES',
    'Create with me ⚡': 'Vamos criar juntos ⚡',
    'Share your profile on your story 📸': 'Compartilhe seu perfil no story 📸',
    'Press and hold the image to save it': 'Segure a imagem para salvá-la',
    'Preparing…': 'Preparando…',
    '📸 Save the image': '📸 Salvar a imagem',
    'Link copied ✓': 'Link copiado ✓',
    '🔗 Copy my link': '🔗 Copiar meu link',
    'Account deleted': 'Conta excluída',
    'Deleted account': 'Conta excluída',
    'This person deleted their account. The conversation stays here, but you can no longer reply.': 'Essa pessoa excluiu a conta. A conversa continua aqui, mas você não pode mais responder.',
    'Please confirm your age and accept the terms to continue.': 'Confirme sua idade e aceite os termos para continuar.',
    'I confirm I am 18 or over': 'Confirmo que tenho 18 anos ou mais',
    ' and I accept the ': ' e aceito os ',
    'This handle is not allowed.': 'Esse handle não é permitido.',
    'This handle is not allowed': 'Esse handle não é permitido',
    'This handle is reserved': 'Esse handle é reservado',
    'Couldn\'t send the photo. Try again.': 'Não deu para enviar a foto. Tente de novo.',
    '📷 Photo': '📷 Foto',
    'Shared photo': 'Foto compartilhada',
    'Send a photo': 'Enviar uma foto',
    'Open to save': 'Abrir para salvar',
    'Your handle needs at least 3 characters.': 'Seu handle precisa de pelo menos 3 caracteres.',
    'This handle is already taken.': 'Esse handle já está em uso.',
    'At least 3 characters: letters, numbers, . or _': 'No mínimo 3 caracteres: letras, números, . ou _',
    'Checking…': 'Verificando…',
    'Already taken': 'Já está em uso',
    '🔍 Search @handle, name, role...': '🔍 Busque um @handle, nome, função...',
    'Tap the link': 'Toque no link',
    'Apply ⚡': 'Candidatar-se ⚡',
    'Terms of Use & Privacy Policy': 'Termos de Uso e Política de Privacidade',
    " of Snappin'Buddy": " do Snappin'Buddy",
    'Accept and continue': 'Aceitar e continuar',
    'On shoot': 'Em ensaio',
    'Unavailable': 'Indisponível',
    'Available': 'Disponível',
    'VIDEO': 'VÍDEO',
    'View on Instagram →': 'Ver no Instagram →',
    'CURRENT PROJECT': 'PROJETO ATUAL',
    'ROLE': 'FUNÇÃO',
    'UNIVERSE': 'UNIVERSO',
    'AREAS': 'ZONAS',
    "✓ Proposal sent! Let's create something beautiful 🎨": '✓ Proposta enviada! Vamos criar algo bonito 🎨',
    'Tell them about your project...': 'Conte sobre o seu projeto...',
    'Sending...': 'Enviando...',
    '⚡ Send proposal': '⚡ Enviar proposta',
    '⚡ Propose a collab': '⚡ Propor uma collab',
    'Report this user': 'Denunciar este usuário',
    'Report sent, thank you.': 'Denúncia enviada, obrigado.',
    'Why are you reporting this user?': 'Por que você está denunciando este usuário?',
    'Inappropriate behavior': 'Comportamento inadequado',
    'Fake profile': 'Perfil falso',
    'Spam': 'Spam',
    'Harassment': 'Assédio',
    'Other': 'Outro',
    'Cancel': 'Cancelar',
    'Send report': 'Enviar',
    'Before you meet': 'Antes do encontro',
    "It all starts here... let's create something beautiful!": 'Tudo começa aqui... vamos criar algo bonito!',
    'Message...': 'Mensagem...',
    'Maximum 5 portfolio photos': 'Máximo de 5 fotos no portfólio',
    'Required fields missing': 'Campos obrigatórios faltando',
    'Edit profile': 'Editar perfil',
    'Name': 'Nome',
    'Your name or username': 'Seu nome ou usuário',
    'Area': 'Região',
    'Shoreditch, Kreuzberg...': 'Vila Madalena, Lapa...',
    'Pitch': 'Pitch',
    'Current project...': 'Seu projeto atual...',
    'VIDEO LINK': 'LINK DO VÍDEO',
    'Saving...': 'Salvando...',
    'Save': 'Salvar',
    'All': 'Todos',
    'CREATIVE': 'CRIATIVO',
    'View': 'Ver',
    'No results': 'Nenhum resultado',
    'Try a different search': 'Tente outra busca',
    'Me': 'Eu',
    'See profile & create together →': 'Ver perfil e criar juntos →',
    'Payment error, try again.': 'Erro no pagamento, tente de novo.',
    "⚡ Let's create something beautiful together! When shall we meet?": '⚡ Vamos criar algo bonito juntos! Quando a gente se encontra?',
    'Accepted ✓': 'Aceita ✓',
    'Declined': 'Recusada',
    'Pending': 'Pendente',
    'View profile': 'Ver perfil',
    'proposal(s)': 'proposta(s)',
    'No proposals yet': 'Nenhuma proposta ainda',
    'Share your project to get proposals!': 'Compartilhe seu projeto para receber propostas!',
    'Open': 'Aberto',
    'Closed': 'Fechado',
    'See proposals →': 'Ver propostas →',
    'Edit': 'Editar',
    'Share': 'Compartilhar',
    '📍 City or country...': '📍 Cidade ou país...',
    'For you': 'Para você',
    'Recent': 'Recentes',
    'MATCHING YOUR PROFILE': 'COMBINA COM O SEU UNIVERSO',
    'Creative': 'Criativo',
    'Share on story': 'Compartilhar nos stories',
    'No message': 'Sem mensagem',
    'en-GB': 'pt-BR',
    'Following ✓': 'Seguindo ✓',
    'Follow': 'Seguir',
    'Following': 'Seguindo',
    'No conversations yet': 'Nenhuma conversa ainda',
    "Creatives you've already collaborated with": 'Criativos com quem você já colaborou',
    'No buddies yet': 'Nenhum buddy ainda',
    'Your accepted collabs will appear here!': 'Suas collabs aceitas vão aparecer aqui!',
    'Your private list of creatives to follow': 'Sua lista privada de criativos para seguir',
    'Nobody yet': 'Ninguém ainda',
    'Follow creatives from Explore or Buddies!': 'Siga criativos pelo Explorar ou Buddies!',
    'Edit project': 'Editar projeto',
    'New project': 'Novo projeto',
    'TITLE *': 'TÍTULO *',
    'Project title *': 'Título do projeto *',
    'DESCRIPTION': 'DESCRIÇÃO',
    'Describe your project...': 'Descreva seu projeto...',
    'WHO ARE YOU LOOKING FOR? *': 'QUEM VOCÊ PROCURA? *',
    'City': 'Cidade',
    'Launching...': 'Lançando...',
    '✓ Save changes': '✓ Salvar alterações',
    '⚡ Launch project': '⚡ Lançar projeto',
    'Close project': 'Encerrar projeto',
    'Please fill in all required fields.': 'Preencha todos os campos obrigatórios.',
    'NAME OR USERNAME *': 'NOME OU USUÁRIO *',
    'Fill in your name and handle first.': 'Preencha primeiro seu nome e seu usuário.',
    'Profile photo': 'Foto de perfil',
    'Role': 'Função',
    'Universe': 'Universo',
    'Complete your profile to be found more easily!': 'Complete seu perfil para ser encontrado mais facilmente!',
    'Good start! The more complete, the more you match': 'Bom começo! Quanto mais completo, mais matches',
    'Almost perfect!': 'Quase perfeito!',
    'Complete profile 🔥 Ready to create something beautiful!': 'Perfil completo 🔥 Pronto para criar algo bonito!',
    'Profile strength': 'Força do perfil',
    'Video': 'Vídeo',
    'My projects': 'Meus projetos',
    'active': 'em andamento',
    '📸 Screenshot this card and share it on your story!': '📸 Tire print deste card e compartilhe nos seus stories!',
    '⚡ PROJECT': '⚡ PROJETO',
    'LOOKING FOR': 'PROCURAMOS',
    'Join ⚡': 'Quero participar ⚡',
    'Close': 'Fechar',
    'Choose a new password': 'Escolha uma nova senha',
    'At least 6 characters.': 'Pelo menos 6 caracteres.',
    'New password': 'Nova senha',
    'Confirm password': 'Confirme a senha',
    'Passwords do not match.': 'As senhas não coincidem.',
    'Password too short (6 characters minimum).': 'Senha muito curta (mínimo de 6 caracteres).',
    'Save password': 'Salvar senha',
    'Password updated! ✓': 'Senha atualizada! ✓',
    'Continue to the app →': 'Continuar para o app →',
    'They will get an email. Once accepted, you can chat.': 'A pessoa vai receber um e-mail. Quando aceitar, vocês podem conversar.',
    'Message': 'Escrever',
    'Proposal sent · waiting for a reply': 'Proposta enviada · aguardando resposta',
    'They already sent you a proposal: reply in Match → 🤝': 'Essa pessoa já te enviou uma proposta: responda em Match → 🤝',
    'Remember to generate and scan your QR codes in the tab': 'Lembrem de gerar e escanear os QR codes na aba',
    'Proposals you receive and send. Accept one to open the chat, then generate your QR code when you meet.': 'As propostas que você recebe e envia. Aceite uma para abrir o chat e gere seu QR code no dia do ensaio.',
    'Reopen project': 'Reabrir o projeto',
    'Deleting...': 'Excluindo...',
    'Tap again to delete for good': 'Toque de novo para excluir de vez',
    'Delete project': 'Excluir o projeto',
    'Could not delete the project, try again.': 'Não foi possível excluir o projeto, tente de novo.',
    'Save the card': 'Salvar o card',
    'Press and hold the image to save it, then share it on your story!': 'Toque e segure a imagem para salvar e depois compartilhe no seu story!',
    '✓ Collab done': '✓ Collab realizada',
    'You': 'Você',
    'Message deleted': 'Mensagem apagada',
    'Replying to': 'Respondendo a',
    'you': 'você',
    'Copied ✓': 'Copiado ✓',
    'Reply': 'Responder',
    'Copy text': 'Copiar o texto',
    'Delete': 'Apagar',
    'edited': 'editada',
    'Editing your message': 'Editando sua mensagem',
    'Forward to': 'Encaminhar para',
    'No buddies to forward to yet.': 'Você ainda não tem buddies para encaminhar.',
    'Pick an emoji': 'Escolher um emoji',
    'Forward': 'Encaminhar',
    'Unpin': 'Desafixar',
    'Pin': 'Fixar',
    'Read receipts': 'Confirmações de leitura',
    'Let others see when you read their messages.': 'Deixe os outros verem quando você lê as mensagens.',
    'ROLES *': 'FUNÇÕES *',
    'Pick up to 3.': 'Escolha até 3.',
    'You can pick up to 3.': 'Você pode escolher até 3.',
    'Choose at least one role.': 'Escolha pelo menos uma função.',
    'This screen had a problem': 'Esta tela teve um problema',
    'The rest of the app still works. Reload to try again.': 'O resto do app funciona. Recarregue para tentar de novo.',
    'Reload': 'Recarregar',
    'Shared project': 'Projeto compartilhado',
    'Tap the link to apply': 'Toque no link para se candidatar',
    'Preparing...': 'Preparando...',
    '⬇️ Save the image': '⬇️ Salvar a imagem',
    '🔗 Copy the link': '🔗 Copiar o link',
    '1. Save the image, then post it on your story.': '1. Salve a imagem e poste no seu story.',
    '2. Copy the link, then add the link sticker and paste it.': '2. Copie o link, adicione o sticker de link e cole.',
    '3. Anyone who taps it lands on this exact project.': '3. Quem tocar cai direto neste projeto.',
    'Press and hold the image to save it.': 'Toque e segure a imagem para salvar.',
  },

  de: {
    'Check your emails': 'Sieh in deine E-Mails',
    'We sent a confirmation link to': 'Wir haben einen Bestätigungslink geschickt an',
    'Click the link to activate your account, then come back here. Check your spam folder if you don’t see it.': 'Klicke auf den Link, um dein Konto zu aktivieren, und komm zurück. Schau im Spam nach, falls er fehlt.',
    'Link sent again ✓': 'Link erneut gesendet ✓',
    'Resend the link': 'Link erneut senden',
    'Back to sign in': 'Zurück zur Anmeldung',
    'validated projects': 'bestätigte Projekte',
    'validated project': 'bestätigtes Projekt',
    'Real meetings, confirmed on the spot': 'Echte Treffen, vor Ort bestätigt',
    'You blocked this person. They can no longer contact you or see your profile.': 'Du hast diese Person blockiert. Sie kann dich nicht mehr kontaktieren oder dein Profil sehen.',
    'Unblock': 'Entsperren',
    'Block this person': 'Diese Person blockieren',
    'They won’t be able to message you, propose a collab, or see you on the map. You can undo this at any time.': 'Sie kann dir nicht mehr schreiben, keine Collab vorschlagen und dich nicht auf der Karte sehen. Du kannst das jederzeit rückgängig machen.',
    'Block': 'Blockieren',
    'Visible on your profile': 'Auf deinem Profil sichtbar',
    'Scan your buddy’s QR when you meet to validate a project': 'Scanne beim Treffen den QR deines Buddys, um ein Projekt zu bestätigen',
    'Blocked accounts': 'Blockierte Konten',
    'Loading…': 'Wird geladen…',
    'You haven’t blocked anyone.': 'Du hast niemanden blockiert.',
    'Sign out on all devices': 'Auf allen Geräten abmelden',
    'Sign in first': 'Melde dich zuerst an',
    'Log in and scan the QR again.': 'Melde dich an und scanne den QR erneut.',
    'That’s your own QR': 'Das ist dein eigener QR',
    'Scan the other person’s QR, not yours.': 'Scanne den QR der anderen Person, nicht deinen.',
    'This QR has expired': 'Dieser QR ist abgelaufen',
    'QR codes last 30 minutes. Ask for a new one.': 'QR-Codes gelten 30 Minuten. Bitte um einen neuen.',
    'Not your collab': 'Nicht deine Collab',
    'This QR belongs to a project you’re not part of.': 'Dieser QR gehört zu einem Projekt, an dem du nicht beteiligt bist.',
    'QR not recognised': 'QR nicht erkannt',
    'This code doesn’t match any meeting.': 'Dieser Code gehört zu keinem Treffen.',
    'Something went wrong': 'Etwas ist schiefgelaufen',
    'Try scanning again.': 'Versuch es noch einmal.',
    'your buddy': 'dein Buddy',
    'Already validated': 'Bereits bestätigt',
    'Meeting validated!': 'Treffen bestätigt!',
    'Share your shoot': 'Teilt euer Shooting',
    'Post a photo from today in your story, tag @snappinbuddy and add #snappinbuddy — the best collabs get reposted on our page.': 'Poste ein Foto von heute in deiner Story, markiere @snappinbuddy und nutze #snappinbuddy — die schönsten Collabs landen auf unserer Seite.',
    'Caption copied ✓': 'Text kopiert ✓',
    'Copy the caption': 'Text kopieren',
    'Back to the app': 'Zurück zur App',
    'Sign out': 'Abmelden',
    'Share my profile': 'Mein Profil teilen',
    'ROLES': 'ROLLEN',
    'Create with me ⚡': 'Lass uns zusammen was machen ⚡',
    'Share your profile on your story 📸': 'Teile dein Profil in deiner Story 📸',
    'Press and hold the image to save it': 'Halte das Bild gedrückt, um es zu speichern',
    'Preparing…': 'Wird vorbereitet…',
    '📸 Save the image': '📸 Bild speichern',
    'Link copied ✓': 'Link kopiert ✓',
    '🔗 Copy my link': '🔗 Meinen Link kopieren',
    'Account deleted': 'Konto gelöscht',
    'Deleted account': 'Gelöschtes Konto',
    'This person deleted their account. The conversation stays here, but you can no longer reply.': 'Diese Person hat ihr Konto gelöscht. Die Unterhaltung bleibt hier, aber du kannst nicht mehr antworten.',
    'Please confirm your age and accept the terms to continue.': 'Bestätige dein Alter und akzeptiere die Bedingungen, um fortzufahren.',
    'I confirm I am 18 or over': 'Ich bestätige, dass ich 18 Jahre oder älter bin',
    ' and I accept the ': ' und ich akzeptiere die ',
    'This handle is not allowed.': 'Dieses Handle ist nicht erlaubt.',
    'This handle is not allowed': 'Dieses Handle ist nicht erlaubt',
    'This handle is reserved': 'Dieses Handle ist reserviert',
    'Couldn\'t send the photo. Try again.': 'Foto konnte nicht gesendet werden. Versuch es nochmal.',
    '📷 Photo': '📷 Foto',
    'Shared photo': 'Geteiltes Foto',
    'Send a photo': 'Foto senden',
    'Open to save': 'Öffnen zum Speichern',
    'Your handle needs at least 3 characters.': 'Dein Handle braucht mindestens 3 Zeichen.',
    'This handle is already taken.': 'Dieses Handle ist schon vergeben.',
    'At least 3 characters: letters, numbers, . or _': 'Mindestens 3 Zeichen: Buchstaben, Zahlen, . oder _',
    'Checking…': 'Wird geprüft…',
    'Already taken': 'Schon vergeben',
    '🔍 Search @handle, name, role...': '🔍 @Handle, Name oder Rolle suchen...',
    'Tap the link': 'Tippe auf den Link',
    'Apply ⚡': 'Bewerben ⚡',
    'Terms of Use & Privacy Policy': 'Nutzungsbedingungen & Datenschutzerklärung',
    " of Snappin'Buddy": " von Snappin'Buddy",
    'Accept and continue': 'Akzeptieren und weiter',
    'On shoot': 'Beim Shooting',
    'Unavailable': 'Nicht verfügbar',
    'Available': 'Verfügbar',
    'VIDEO': 'VIDEO',
    'View on Instagram →': 'Auf Instagram ansehen →',
    'CURRENT PROJECT': 'AKTUELLES PROJEKT',
    'ROLE': 'ROLLE',
    'UNIVERSE': 'UNIVERSUM',
    'AREAS': 'ZONEN',
    "✓ Proposal sent! Let's create something beautiful 🎨": '✓ Vorschlag gesendet! Lasst uns etwas Schönes erschaffen 🎨',
    'Tell them about your project...': 'Erzähl von deinem Projekt...',
    'Sending...': 'Wird gesendet...',
    '⚡ Send proposal': '⚡ Vorschlag senden',
    '⚡ Propose a collab': '⚡ Eine Collab vorschlagen',
    'Report this user': 'Diese Person melden',
    'Report sent, thank you.': 'Meldung gesendet, danke.',
    'Why are you reporting this user?': 'Warum meldest du diese Person?',
    'Inappropriate behavior': 'Unangemessenes Verhalten',
    'Fake profile': 'Fake-Profil',
    'Spam': 'Spam',
    'Harassment': 'Belästigung',
    'Other': 'Sonstiges',
    'Cancel': 'Abbrechen',
    'Send report': 'Senden',
    'Before you meet': 'Vor eurem Treffen',
    "It all starts here... let's create something beautiful!": 'Hier fängt alles an... lasst uns etwas Schönes erschaffen!',
    'Message...': 'Nachricht...',
    'Maximum 5 portfolio photos': 'Maximal 5 Portfolio-Fotos',
    'Required fields missing': 'Pflichtfelder fehlen',
    'Edit profile': 'Profil bearbeiten',
    'Name': 'Name',
    'Your name or username': 'Dein Name oder Username',
    'Area': 'Gegend',
    'Shoreditch, Kreuzberg...': 'Kreuzberg, Schanzenviertel...',
    'Pitch': 'Pitch',
    'Current project...': 'Dein aktuelles Projekt...',
    'VIDEO LINK': 'VIDEO-LINK',
    'Saving...': 'Wird gespeichert...',
    'Save': 'Speichern',
    'All': 'Alle',
    'CREATIVE': 'KREATIVE',
    'View': 'Ansehen',
    'No results': 'Keine Ergebnisse',
    'Try a different search': 'Versuch eine andere Suche',
    'Me': 'Ich',
    'See profile & create together →': 'Profil ansehen & zusammen kreieren →',
    'Payment error, try again.': 'Zahlungsfehler, versuch es noch einmal.',
    "⚡ Let's create something beautiful together! When shall we meet?": '⚡ Lass uns zusammen etwas Schönes erschaffen! Wann treffen wir uns?',
    'Accepted ✓': 'Angenommen ✓',
    'Declined': 'Abgelehnt',
    'Pending': 'Ausstehend',
    'View profile': 'Profil ansehen',
    'proposal(s)': 'Vorschlag/Vorschläge',
    'No proposals yet': 'Noch keine Vorschläge',
    'Share your project to get proposals!': 'Teile dein Projekt, um Vorschläge zu bekommen!',
    'Open': 'Offen',
    'Closed': 'Geschlossen',
    'See proposals →': 'Vorschläge ansehen →',
    'Edit': 'Bearbeiten',
    'Share': 'Teilen',
    '📍 City or country...': '📍 Stadt oder Land...',
    'For you': 'Für dich',
    'Recent': 'Neueste',
    'MATCHING YOUR PROFILE': 'PASST ZU DEINEM UNIVERSUM',
    'Creative': 'Kreative:r',
    'Share on story': 'In der Story teilen',
    'No message': 'Keine Nachricht',
    'en-GB': 'de-DE',
    'Following ✓': 'Folgst du ✓',
    'Follow': 'Folgen',
    'Following': 'Gefolgt',
    'No conversations yet': 'Noch keine Unterhaltungen',
    "Creatives you've already collaborated with": 'Kreative, mit denen du schon zusammengearbeitet hast',
    'No buddies yet': 'Noch keine Buddies',
    'Your accepted collabs will appear here!': 'Deine angenommenen Collabs erscheinen hier!',
    'Your private list of creatives to follow': 'Deine private Liste von Kreativen, denen du folgst',
    'Nobody yet': 'Noch niemand',
    'Follow creatives from Explore or Buddies!': 'Folge Kreativen über Entdecken oder Buddies!',
    'Edit project': 'Projekt bearbeiten',
    'New project': 'Neues Projekt',
    'TITLE *': 'TITEL *',
    'Project title *': 'Projekttitel *',
    'DESCRIPTION': 'BESCHREIBUNG',
    'Describe your project...': 'Beschreib dein Projekt...',
    'WHO ARE YOU LOOKING FOR? *': 'WEN SUCHST DU? *',
    'City': 'Stadt',
    'Launching...': 'Wird gestartet...',
    '✓ Save changes': '✓ Änderungen speichern',
    '⚡ Launch project': '⚡ Projekt starten',
    'Close project': 'Projekt schließen',
    'Please fill in all required fields.': 'Bitte fülle alle Pflichtfelder aus.',
    'NAME OR USERNAME *': 'NAME ODER USERNAME *',
    'Fill in your name and handle first.': 'Gib zuerst deinen Namen und dein Handle ein.',
    'Profile photo': 'Profilfoto',
    'Role': 'Rolle',
    'Universe': 'Universum',
    'Complete your profile to be found more easily!': 'Vervollständige dein Profil, damit man dich leichter findet!',
    'Good start! The more complete, the more you match': 'Guter Anfang! Je vollständiger, desto mehr Matches',
    'Almost perfect!': 'Fast perfekt!',
    'Complete profile 🔥 Ready to create something beautiful!': 'Profil vollständig 🔥 Bereit, etwas Schönes zu erschaffen!',
    'Profile strength': 'Profilstärke',
    'Video': 'Video',
    'My projects': 'Meine Projekte',
    'active': 'aktiv',
    '📸 Screenshot this card and share it on your story!': '📸 Mach einen Screenshot dieser Karte und teile sie in deiner Story!',
    '⚡ PROJECT': '⚡ PROJEKT',
    'LOOKING FOR': 'GESUCHT',
    'Join ⚡': 'Ich bin dabei ⚡',
    'Close': 'Schließen',
    'Choose a new password': 'Wähle ein neues Passwort',
    'At least 6 characters.': 'Mindestens 6 Zeichen.',
    'New password': 'Neues Passwort',
    'Confirm password': 'Passwort bestätigen',
    'Passwords do not match.': 'Die Passwörter stimmen nicht überein.',
    'Password too short (6 characters minimum).': 'Passwort zu kurz (mindestens 6 Zeichen).',
    'Save password': 'Passwort speichern',
    'Password updated! ✓': 'Passwort aktualisiert! ✓',
    'Continue to the app →': 'Weiter zur App →',
    'They will get an email. Once accepted, you can chat.': 'Die Person bekommt eine E-Mail. Sobald sie annimmt, könnt ihr chatten.',
    'Message': 'Schreiben',
    'Proposal sent · waiting for a reply': 'Vorschlag gesendet · wartet auf Antwort',
    'They already sent you a proposal: reply in Match → 🤝': 'Diese Person hat dir schon einen Vorschlag geschickt: antworte unter Match → 🤝',
    'Remember to generate and scan your QR codes in the tab': 'Denkt daran, eure QR-Codes im Tab zu erstellen und zu scannen',
    'Proposals you receive and send. Accept one to open the chat, then generate your QR code when you meet.': 'Deine empfangenen und gesendeten Vorschläge. Nimm einen an, um den Chat zu öffnen, und erstelle beim Treffen deinen QR-Code.',
    'Reopen project': 'Projekt wieder öffnen',
    'Deleting...': 'Wird gelöscht...',
    'Tap again to delete for good': 'Tippe nochmal, um endgültig zu löschen',
    'Delete project': 'Projekt löschen',
    'Could not delete the project, try again.': 'Projekt konnte nicht gelöscht werden, versuch es nochmal.',
    'Save the card': 'Karte speichern',
    'Press and hold the image to save it, then share it on your story!': 'Halte das Bild gedrückt, um es zu speichern, und teile es dann in deiner Story!',
    '✓ Collab done': '✓ Collab umgesetzt',
    'You': 'Du',
    'Message deleted': 'Nachricht gelöscht',
    'Replying to': 'Antwort an',
    'you': 'dich',
    'Copied ✓': 'Kopiert ✓',
    'Reply': 'Antworten',
    'Copy text': 'Text kopieren',
    'Delete': 'Löschen',
    'edited': 'bearbeitet',
    'Editing your message': 'Du bearbeitest deine Nachricht',
    'Forward to': 'Weiterleiten an',
    'No buddies to forward to yet.': 'Noch keine Buddies zum Weiterleiten.',
    'Pick an emoji': 'Emoji auswählen',
    'Forward': 'Weiterleiten',
    'Unpin': 'Loslösen',
    'Pin': 'Anheften',
    'Read receipts': 'Lesebestätigungen',
    'Let others see when you read their messages.': 'Zeige anderen, wann du ihre Nachrichten liest.',
    'ROLES *': 'ROLLEN *',
    'Pick up to 3.': 'Wähle bis zu 3 aus.',
    'You can pick up to 3.': 'Du kannst bis zu 3 auswählen.',
    'Choose at least one role.': 'Wähle mindestens eine Rolle.',
    'This screen had a problem': 'Auf diesem Bildschirm gab es ein Problem',
    'The rest of the app still works. Reload to try again.': 'Der Rest der App funktioniert. Lade neu, um es erneut zu versuchen.',
    'Reload': 'Neu laden',
    'Shared project': 'Geteiltes Projekt',
    'Tap the link to apply': 'Tippe auf den Link, um dich zu bewerben',
    'Preparing...': 'Wird vorbereitet...',
    '⬇️ Save the image': '⬇️ Bild speichern',
    '🔗 Copy the link': '🔗 Link kopieren',
    '1. Save the image, then post it on your story.': '1. Speichere das Bild und poste es in deiner Story.',
    '2. Copy the link, then add the link sticker and paste it.': '2. Kopiere den Link, füge den Link-Sticker ein und setze ihn ein.',
    '3. Anyone who taps it lands on this exact project.': '3. Wer darauf tippt, landet direkt bei diesem Projekt.',
    'Press and hold the image to save it.': 'Halte das Bild gedrückt, um es zu speichern.',
  },

  it: {
    'Check your emails': 'Controlla le tue email',
    'We sent a confirmation link to': 'Abbiamo inviato un link di conferma a',
    'Click the link to activate your account, then come back here. Check your spam folder if you don’t see it.': 'Clicca sul link per attivare il tuo account, poi torna qui. Controlla lo spam se non lo trovi.',
    'Link sent again ✓': 'Link inviato di nuovo ✓',
    'Resend the link': 'Invia di nuovo il link',
    'Back to sign in': 'Torna all’accesso',
    'validated projects': 'progetti validati',
    'validated project': 'progetto validato',
    'Real meetings, confirmed on the spot': 'Incontri reali, confermati sul posto',
    'You blocked this person. They can no longer contact you or see your profile.': 'Hai bloccato questa persona. Non può più contattarti né vedere il tuo profilo.',
    'Unblock': 'Sblocca',
    'Block this person': 'Blocca questa persona',
    'They won’t be able to message you, propose a collab, or see you on the map. You can undo this at any time.': 'Non potrà scriverti, proporti una collab né vederti sulla mappa. Puoi annullare quando vuoi.',
    'Block': 'Blocca',
    'Visible on your profile': 'Visibile sul tuo profilo',
    'Scan your buddy’s QR when you meet to validate a project': 'Scansiona il QR del tuo buddy quando vi incontrate per validare un progetto',
    'Blocked accounts': 'Account bloccati',
    'Loading…': 'Caricamento…',
    'You haven’t blocked anyone.': 'Non hai bloccato nessuno.',
    'Sign out on all devices': 'Esci da tutti i dispositivi',
    'Sign in first': 'Accedi prima',
    'Log in and scan the QR again.': 'Accedi e scansiona di nuovo il QR.',
    'That’s your own QR': 'È il tuo stesso QR',
    'Scan the other person’s QR, not yours.': 'Scansiona il QR dell’altra persona, non il tuo.',
    'This QR has expired': 'Questo QR è scaduto',
    'QR codes last 30 minutes. Ask for a new one.': 'I QR durano 30 minuti. Chiedine uno nuovo.',
    'Not your collab': 'Non è la tua collab',
    'This QR belongs to a project you’re not part of.': 'Questo QR appartiene a un progetto di cui non fai parte.',
    'QR not recognised': 'QR non riconosciuto',
    'This code doesn’t match any meeting.': 'Questo codice non corrisponde a nessun incontro.',
    'Something went wrong': 'Qualcosa è andato storto',
    'Try scanning again.': 'Riprova a scansionare.',
    'your buddy': 'il tuo buddy',
    'Already validated': 'Già validato',
    'Meeting validated!': 'Incontro validato!',
    'Share your shoot': 'Condividete lo shooting',
    'Post a photo from today in your story, tag @snappinbuddy and add #snappinbuddy — the best collabs get reposted on our page.': 'Pubblica una foto di oggi nella storia, tagga @snappinbuddy e aggiungi #snappinbuddy — le collab più belle finiscono sulla nostra pagina.',
    'Caption copied ✓': 'Didascalia copiata ✓',
    'Copy the caption': 'Copia la didascalia',
    'Back to the app': 'Torna all’app',
    'Sign out': 'Esci',
    'Share my profile': 'Condividi il mio profilo',
    'ROLES': 'RUOLI',
    'Create with me ⚡': 'Creiamo insieme ⚡',
    'Share your profile on your story 📸': 'Condividi il tuo profilo nella storia 📸',
    'Press and hold the image to save it': 'Tieni premuta l’immagine per salvarla',
    'Preparing…': 'Preparazione…',
    '📸 Save the image': '📸 Salva l’immagine',
    'Link copied ✓': 'Link copiato ✓',
    '🔗 Copy my link': '🔗 Copia il mio link',
    'Account deleted': 'Account eliminato',
    'Deleted account': 'Account eliminato',
    'This person deleted their account. The conversation stays here, but you can no longer reply.': 'Questa persona ha eliminato il suo account. La conversazione resta qui, ma non puoi più rispondere.',
    'Please confirm your age and accept the terms to continue.': 'Conferma la tua età e accetta le condizioni per continuare.',
    'I confirm I am 18 or over': 'Confermo di avere 18 anni o più',
    ' and I accept the ': ' e accetto le ',
    'This handle is not allowed.': 'Questo handle non è consentito.',
    'This handle is not allowed': 'Questo handle non è consentito',
    'This handle is reserved': 'Questo handle è riservato',
    'Couldn\'t send the photo. Try again.': 'Invio della foto non riuscito. Riprova.',
    '📷 Photo': '📷 Foto',
    'Shared photo': 'Foto condivisa',
    'Send a photo': 'Invia una foto',
    'Open to save': 'Apri per salvare',
    'Your handle needs at least 3 characters.': 'Il tuo handle deve avere almeno 3 caratteri.',
    'This handle is already taken.': 'Questo handle è già preso.',
    'At least 3 characters: letters, numbers, . or _': 'Almeno 3 caratteri: lettere, numeri, . o _',
    'Checking…': 'Controllo…',
    'Already taken': 'Già preso',
    '🔍 Search @handle, name, role...': '🔍 Cerca un @handle, nome, ruolo...',
    'Tap the link': 'Tocca il link',
    'Apply ⚡': 'Candidati ⚡',
    'Terms of Use & Privacy Policy': 'Termini d’uso e Informativa sulla privacy',
    " of Snappin'Buddy": " di Snappin'Buddy",
    'Accept and continue': 'Accetta e continua',
    'On shoot': 'In shooting',
    'Unavailable': 'Non disponibile',
    'Available': 'Disponibile',
    'VIDEO': 'VIDEO',
    'View on Instagram →': 'Guarda su Instagram →',
    'CURRENT PROJECT': 'PROGETTO ATTUALE',
    'ROLE': 'RUOLO',
    'UNIVERSE': 'UNIVERSO',
    'AREAS': 'ZONE',
    "✓ Proposal sent! Let's create something beautiful 🎨": '✓ Proposta inviata! Creiamo qualcosa di bello 🎨',
    'Tell them about your project...': 'Raccontagli il tuo progetto...',
    'Sending...': 'Invio...',
    '⚡ Send proposal': '⚡ Invia la proposta',
    '⚡ Propose a collab': '⚡ Proponi una collab',
    'Report this user': 'Segnala questo utente',
    'Report sent, thank you.': 'Segnalazione inviata, grazie.',
    'Why are you reporting this user?': 'Perché segnali questo utente?',
    'Inappropriate behavior': 'Comportamento inappropriato',
    'Fake profile': 'Profilo falso',
    'Spam': 'Spam',
    'Harassment': 'Molestie',
    'Other': 'Altro',
    'Cancel': 'Annulla',
    'Send report': 'Invia',
    'Before you meet': 'Prima di incontrarvi',
    "It all starts here... let's create something beautiful!": 'Tutto inizia qui... creiamo qualcosa di bello!',
    'Message...': 'Messaggio...',
    'Maximum 5 portfolio photos': 'Massimo 5 foto nel portfolio',
    'Required fields missing': 'Campi obbligatori mancanti',
    'Edit profile': 'Modifica profilo',
    'Name': 'Nome',
    'Your name or username': 'Il tuo nome o username',
    'Area': 'Zona',
    'Shoreditch, Kreuzberg...': 'Navigli, Trastevere...',
    'Pitch': 'Pitch',
    'Current project...': 'Il tuo progetto attuale...',
    'VIDEO LINK': 'LINK VIDEO',
    'Saving...': 'Salvataggio...',
    'Save': 'Salva',
    'All': 'Tutti',
    'CREATIVE': 'CREATIVO',
    'View': 'Vedi',
    'No results': 'Nessun risultato',
    'Try a different search': 'Prova un’altra ricerca',
    'Me': 'Io',
    'See profile & create together →': 'Vedi il profilo e create insieme →',
    'Payment error, try again.': 'Errore di pagamento, riprova.',
    "⚡ Let's create something beautiful together! When shall we meet?": '⚡ Creiamo qualcosa di bello insieme! Quando ci vediamo?',
    'Accepted ✓': 'Accettata ✓',
    'Declined': 'Rifiutata',
    'Pending': 'In attesa',
    'View profile': 'Vedi profilo',
    'proposal(s)': 'proposta/e',
    'No proposals yet': 'Ancora nessuna proposta',
    'Share your project to get proposals!': 'Condividi il tuo progetto per ricevere proposte!',
    'Open': 'Aperto',
    'Closed': 'Chiuso',
    'See proposals →': 'Vedi proposte →',
    'Edit': 'Modifica',
    'Share': 'Condividi',
    '📍 City or country...': '📍 Città o paese...',
    'For you': 'Per te',
    'Recent': 'Recenti',
    'MATCHING YOUR PROFILE': 'IN LINEA CON IL TUO UNIVERSO',
    'Creative': 'Creativo',
    'Share on story': 'Condividi nelle storie',
    'No message': 'Nessun messaggio',
    'en-GB': 'it-IT',
    'Following ✓': 'Segui già ✓',
    'Follow': 'Segui',
    'Following': 'Seguiti',
    'No conversations yet': 'Ancora nessuna conversazione',
    "Creatives you've already collaborated with": 'Creativi con cui hai già collaborato',
    'No buddies yet': 'Ancora nessun buddy',
    'Your accepted collabs will appear here!': 'Le tue collab accettate appariranno qui!',
    'Your private list of creatives to follow': 'La tua lista privata di creativi da seguire',
    'Nobody yet': 'Ancora nessuno',
    'Follow creatives from Explore or Buddies!': 'Segui i creativi da Esplora o Buddies!',
    'Edit project': 'Modifica progetto',
    'New project': 'Nuovo progetto',
    'TITLE *': 'TITOLO *',
    'Project title *': 'Titolo del progetto *',
    'DESCRIPTION': 'DESCRIZIONE',
    'Describe your project...': 'Descrivi il tuo progetto...',
    'WHO ARE YOU LOOKING FOR? *': 'CHI CERCHI? *',
    'City': 'Città',
    'Launching...': 'Lancio in corso...',
    '✓ Save changes': '✓ Salva modifiche',
    '⚡ Launch project': '⚡ Lancia il progetto',
    'Close project': 'Chiudi il progetto',
    'Please fill in all required fields.': 'Compila tutti i campi obbligatori.',
    'NAME OR USERNAME *': 'NOME O USERNAME *',
    'Fill in your name and handle first.': 'Inserisci prima il tuo nome e il tuo handle.',
    'Profile photo': 'Foto profilo',
    'Role': 'Ruolo',
    'Universe': 'Universo',
    'Complete your profile to be found more easily!': 'Completa il profilo per farti trovare più facilmente!',
    'Good start! The more complete, the more you match': 'Buon inizio! Più è completo, più match fai',
    'Almost perfect!': 'Quasi perfetto!',
    'Complete profile 🔥 Ready to create something beautiful!': 'Profilo completo 🔥 Pronto a creare qualcosa di bello!',
    'Profile strength': 'Forza del profilo',
    'Video': 'Video',
    'My projects': 'I miei progetti',
    'active': 'in corso',
    '📸 Screenshot this card and share it on your story!': '📸 Fai uno screenshot di questa card e condividila nelle storie!',
    '⚡ PROJECT': '⚡ PROGETTO',
    'LOOKING FOR': 'CERCHIAMO',
    'Join ⚡': 'Ci sto ⚡',
    'Close': 'Chiudi',
    'Choose a new password': 'Scegli una nuova password',
    'At least 6 characters.': 'Almeno 6 caratteri.',
    'New password': 'Nuova password',
    'Confirm password': 'Conferma la password',
    'Passwords do not match.': 'Le password non corrispondono.',
    'Password too short (6 characters minimum).': 'Password troppo corta (minimo 6 caratteri).',
    'Save password': 'Salva la password',
    'Password updated! ✓': 'Password aggiornata! ✓',
    'Continue to the app →': 'Continua nell’app →',
    'They will get an email. Once accepted, you can chat.': 'Riceverà un’email. Quando accetta, potrete chattare.',
    'Message': 'Scrivi',
    'Proposal sent · waiting for a reply': 'Proposta inviata · in attesa di risposta',
    'They already sent you a proposal: reply in Match → 🤝': 'Ti ha già inviato una proposta: rispondi in Match → 🤝',
    'Remember to generate and scan your QR codes in the tab': 'Ricordatevi di generare e scansionare i vostri QR code nella scheda',
    'Proposals you receive and send. Accept one to open the chat, then generate your QR code when you meet.': 'Le proposte che ricevi e invii. Accettane una per aprire la chat, poi genera il tuo QR code il giorno dello shooting.',
    'Reopen project': 'Riapri il progetto',
    'Deleting...': 'Eliminazione...',
    'Tap again to delete for good': 'Tocca di nuovo per eliminarlo definitivamente',
    'Delete project': 'Elimina il progetto',
    'Could not delete the project, try again.': 'Impossibile eliminare il progetto, riprova.',
    'Save the card': 'Salva la card',
    'Press and hold the image to save it, then share it on your story!': 'Tieni premuta l’immagine per salvarla, poi condividila nella tua storia!',
    '✓ Collab done': '✓ Collab realizzata',
    'You': 'Tu',
    'Message deleted': 'Messaggio eliminato',
    'Replying to': 'In risposta a',
    'you': 'te',
    'Copied ✓': 'Copiato ✓',
    'Reply': 'Rispondi',
    'Copy text': 'Copia il testo',
    'Delete': 'Elimina',
    'edited': 'modificato',
    'Editing your message': 'Stai modificando il messaggio',
    'Forward to': 'Inoltra a',
    'No buddies to forward to yet.': 'Non hai ancora buddy a cui inoltrare.',
    'Pick an emoji': 'Scegli un emoji',
    'Forward': 'Inoltra',
    'Unpin': 'Rimuovi dai fissati',
    'Pin': 'Fissa',
    'Read receipts': 'Conferme di lettura',
    'Let others see when you read their messages.': 'Mostra agli altri quando leggi i loro messaggi.',
    'ROLES *': 'RUOLI *',
    'Pick up to 3.': 'Scegline fino a 3.',
    'You can pick up to 3.': 'Puoi sceglierne fino a 3.',
    'Choose at least one role.': 'Scegli almeno un ruolo.',
    'This screen had a problem': 'Questa schermata ha avuto un problema',
    'The rest of the app still works. Reload to try again.': 'Il resto dell’app funziona. Ricarica per riprovare.',
    'Reload': 'Ricarica',
    'Shared project': 'Progetto condiviso',
    'Tap the link to apply': 'Tocca il link per candidarti',
    'Preparing...': 'Preparazione...',
    '⬇️ Save the image': '⬇️ Salva l’immagine',
    '🔗 Copy the link': '🔗 Copia il link',
    '1. Save the image, then post it on your story.': '1. Salva l’immagine e pubblicala nella tua storia.',
    '2. Copy the link, then add the link sticker and paste it.': '2. Copia il link, aggiungi lo sticker link e incollalo.',
    '3. Anyone who taps it lands on this exact project.': '3. Chi tocca il link arriva direttamente su questo progetto.',
    'Press and hold the image to save it.': 'Tieni premuta l’immagine per salvarla.',
  },
};

export default TX;
